- 👋 Hi, I’m @AgatoR4
- 👀 I’m interested in Business, programming, sales, marketing and ecommerce.
- 🌱 I’m currently learning Computer Science
- 💞️ I’m looking to collaborate on projects and business
- 📫 IG: AgatoXR
